### ISSUE TITLE
Passwords ending in !

### ISSUE THREAD

**Issue by SquirrelAssassin** [erfg12/BingRewards#2]
I have a password that ends in a !

What ends up happening is it types out the password except the ! at the end of the password.

If I put in some bogus password I can see it does enter it and clicks submit.  

I tried a few escape characters but nothing seems to help. 

Any thoughts?

**Comment by erfg12** [comment]
The section that parses the code is at https://github.com/erfg12/BingRewards/blob/master/bingRewards/Miner.cs#L256

The section that sends the password to autoitx to type it in is at https://github.com/erfg12/BingRewards/blob/master/bingRewards/Miner.cs#L339

This looks like an issue with AutoItX - https://www.autoitscript.com/forum/topic/61874-how-to-get-an-exclamation-mark-in-a-string/

I'll probably have to build some parsing code to send literals when needed.

**Comment by erfg12** [comment]
Possible fix pushed to source. Try compiling and see if that fixes it.
I uploaded a new setup zip just in case this does fix the issue.

**Comment by SquirrelAssassin** [comment]
Works great thanks!
